import rightsection from '../RightSection/rightsection.module.css'

const RightSection = () => {

    return (
        <div className={rightsection.mainComponent}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Semper viverra nam libero justo. At in tellus integer feugiat scelerisque varius morbi. Faucibus nisl tincidunt eget nullam non nisi est. Faucibus in ornare quam viverra orci. Arcu odio ut sem nulla. Sociis natoque penatibus et magnis dis parturient montes nascetur. Interdum velit euismod in pellentesque massa. Fames ac turpis egestas maecenas. Euismod elementum nisi quis eleifend quam adipiscing. Pretium nibh ipsum consequat nisl vel.

Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Interdum velit euismod in pellentesque massa placerat. Amet venenatis urna cursus eget nunc scelerisque viverra. Est placerat in egestas erat imperdiet sed euismod nisi. Integer enim neque volutpat ac tincidunt vitae. Tortor vitae purus faucibus ornare suspendisse sed nisi lacus. Orci dapibus ultrices in iaculis nunc. Morbi tristique senectus et netus et malesuada fames ac. Vestibulum lectus mauris ultrices eros in cursus turpis. Nisl purus in mollis nunc sed id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames.

Tellus at urna condimentum mattis pellentesque id nibh tortor id. Eu sem integer vitae justo eget magna fermentum iaculis. Vitae congue mauris rhoncus aenean vel. Diam sollicitudin tempor id eu nisl nunc mi ipsum. Lorem ipsum dolor sit amet. Ac placerat vestibulum lectus mauris ultrices. Maecenas ultricies mi eget mauris. Est ante in nibh mauris. Eros donec ac odio tempor orci. Cursus sit amet dictum sit amet justo. Nunc eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Facilisis leo vel fringilla est ullamcorper.

Pulvinar pellentesque habitant morbi tristique senectus. Odio morbi quis commodo odio aenean sed. Nulla facilisi cras fermentum odio eu. Ante in nibh mauris cursus. Proin sed libero enim sed. Ac tortor vitae purus faucibus ornare suspendisse sed nisi. Mattis vulputate enim nulla aliquet. Consectetur libero id faucibus nisl tincidunt eget nullam. A erat nam at lectus. Sit amet cursus sit amet dictum sit amet justo. Suspendisse potenti nullam ac tortor vitae. Odio tempor orci dapibus ultrices in iaculis nunc. At tellus at urna condimentum mattis. Leo vel orci porta non pulvinar neque. Nibh tellus molestie nunc non.

Nullam vehicula ipsum a arcu cursus vitae. Sed enim ut sem viverra aliquet eget sit. Ac tortor dignissim convallis aenean et tortor. Vestibulum lectus mauris ultrices eros in cursus turpis massa tincidunt. Lorem ipsum dolor sit amet consectetur adipiscing elit. Egestas egestas fringilla phasellus faucibus scelerisque. Mi proin sed libero enim sed faucibus turpis in. Urna duis convallis convallis tellus id interdum. Tellus elementum sagittis vitae et leo duis ut diam quam. Odio euismod lacinia at quis risus sed. Feugiat scelerisque varius morbi enim nunc faucibus. Facilisis volutpat est velit egestas dui id ornare arcu odio.

Amet cursus sit amet dictum sit amet justo donec. Lectus quam id leo in. Elementum integer enim neque volutpat ac tincidunt. Id ornare arcu odio ut sem nulla pharetra diam sit. Ornare arcu odio ut sem nulla pharetra diam sit. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Lectus quam id leo in vitae turpis. Sed odio morbi quis commodo odio aenean. Nulla facilisi cras fermentum odio eu feugiat pretium nibh. Lacus vel facilisis volutpat est velit egestas dui id ornare.

Ullamcorper a lacus vestibulum sed. Cras pulvinar mattis nunc sed blandit libero volutpat sed. Lectus sit amet est placerat in egestas erat imperdiet sed. Ornare quam viverra orci sagittis. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Enim blandit volutpat maecenas volutpat blandit. Nunc congue nisi vitae suscipit tellus mauris a. Lorem ipsum dolor sit amet. Neque aliquam vestibulum morbi blandit cursus risus at. Tellus at urna condimentum mattis pellentesque. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Integer quis auctor elit sed vulputate. Tortor at risus viverra adipiscing at. Proin sed libero enim sed faucibus turpis. Velit euismod in pellentesque massa placerat duis ultricies lacus. Sit amet cursus sit amet dictum sit amet justo donec. Et tortor at risus viverra adipiscing at in. Amet justo donec enim diam vulputate. Elementum eu facilisis sed odio morbi quis commodo odio.

Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Amet aliquam id diam maecenas ultricies mi. Iaculis nunc sed augue lacus viverra vitae congue eu. Vitae nunc sed velit dignissim sodales ut eu sem. Tortor at risus viverra adipiscing at. Volutpat ac tincidunt vitae semper. Amet dictum sit amet justo. Eget dolor morbi non arcu. Faucibus nisl tincidunt eget nullam non. Tincidunt id aliquet risus feugiat in ante metus dictum. Morbi quis commodo odio aenean.

Commodo ullamcorper a lacus vestibulum sed arcu. Fusce ut placerat orci nulla pellentesque dignissim enim sit. Pellentesque habitant morbi tristique senectus. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Lacinia quis vel eros donec ac odio tempor orci. Id donec ultrices tincidunt arcu non sodales neque sodales ut. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Fringilla ut morbi tincidunt augue interdum velit euismod in. Eleifend mi in nulla posuere sollicitudin aliquam ultrices. Egestas diam in arcu cursus.

Volutpat odio facilisis mauris sit. Vulputate sapien nec sagittis aliquam malesuada bibendum. Suspendisse ultrices gravida dictum fusce ut placerat. In ante metus dictum at tempor commodo ullamcorper a. Lobortis mattis aliquam faucibus purus in massa tempor nec. Sit amet commodo nulla facilisi nullam vehicula ipsum. Enim ut sem viverra aliquet. Amet justo donec enim diam vulputate ut pharetra. Tortor at auctor urna nunc id cursus metus. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in. Accumsan in nisl nisi scelerisque eu ultrices. Donec enim diam vulputate ut pharetra. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Ut consequat semper viverra nam libero. Vestibulum sed arcu non odio euismod lacinia at. Urna nunc id cursus metus aliquam eleifend mi in. Cras adipiscing enim eu turpis egestas pretium aenean pharetra magna. Non diam phasellus vestibulum lorem sed.  </p>
        </div>
    )
}

export default RightSection